### PR TITLE
Color spaces JS API

### PR DESCRIPTION
**Pull request by jamesnw**
## Description
Exposes a JS API for the Color Spaces proposal

[Rendered Proposal](https://github.com/oddbird/sass/blob/color-spaces-js/proposal/color-4-new-spaces-js.d.ts.md)

### CODE REVIEW

**Comment by jamesnw** [comment]
https://trello.com/c/2R7Mnj6s/1-i-want-js-users-to-have-access-to-new-color-spaces

**Comment by jgerigmeyer** [comment]
[I want JS users to have access to new color spaces.](https://trello.com/c/2R7Mnj6s/1-i-want-js-users-to-have-access-to-new-color-spaces)

**Comment by jamesnw** [comment]
Moved to https://github.com/sass/sass/pull/3665

**Comment by jamesnw** [comment]
[I want JS users to have access to new color spaces.](https://trello.com/c/2R7Mnj6s/1-i-want-js-users-to-have-access-to-new-color-spaces)

**Pull request closed without merging**
